[world]
name = "Provable Games"
description = "DNC"
seed = "test_ls_0_4"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[namespace]
default = "ls_0_0_1"

[writers]
"ls_0_0_1" = ["ls_0_0_1-game_systems", "ls_0_0_1-game_token_systems", "ls_0_0_1-settings_systems"]

[init_call_args]
"ls_0_0_1-game_token_systems" = [
    "0x0238df9Efd27Aba2ccB0bdC97a4cf440caA403e9ed3f1883294Ab6CDBA6C5282",
    "0x012bb7287df14a1c37cb99f74cadac83f76071c366975071103fce5eccdec6c8" # denshokan_address
]