[world]
name = "Death Mountain"
description = "Onchain Dungeon Creator"
seed = "death_mountain"

[writers]
"death_mountain" = ["death_mountain-game_systems", "death_mountain-game_token_systems"]

[init_call_args]
"death_mountain-game_token_systems" = [
    "0x0238df9Efd27Aba2ccB0bdC97a4cf440caA403e9ed3f1883294Ab6CDBA6C5282",
]