[package]
cairo-version = "=2.10.1"
name = "death_mountain"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
game_components_minigame_token = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_minigame = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_minigame_settings = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_minigame_objectives = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components", branch = "main" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }
denshokan = { git = "https://github.com/Provable-Games/denshokan", branch = "main" }


[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "denshokan::models::denshokan::m_GameMetadata",
    "denshokan::models::denshokan::m_GameRegistry",
    "denshokan::models::denshokan::m_GameRegistryId",
    "denshokan::models::denshokan::m_GameCounter",
    "denshokan::models::denshokan::m_MinterRegistry",
    "denshokan::models::denshokan::m_MinterRegistryId",
    "denshokan::models::denshokan::m_MinterCounter",
    "denshokan::models::denshokan::m_TokenMetadata",
    "denshokan::models::denshokan::m_TokenCounter",
    "denshokan::models::denshokan::m_TokenPlayerName",
    "denshokan::models::denshokan::m_TokenObjective",
    "denshokan::denshokan::denshokan::e_Owners",
    "denshokan::denshokan::denshokan::e_ScoreUpdate",
    "denshokan::denshokan::denshokan::e_ObjectiveData",
    "denshokan::denshokan::denshokan::e_SettingsData",
    "denshokan::denshokan::denshokan::e_TokenContextData",
    "denshokan::denshokan::denshokan",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]
