world_address = "0x05246cbbe2bef7fd190adbf05e47bee876ab2ab0e272c3346e0e760cd26adaa7"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[events]
raw = true

[sql]
historical = ["ls_0_0_1-GameEvent"]

[indexing]
pending = true
contracts = [
    "erc721:0x6f261eba018dda4f60bdc1d0874cb7e97bf424979dda63fcbdf8bdcba1fb644"
]