name: test-contracts
# Test caching performance on second run

env:
  SCARB_VERSION: 2.10.1
  DOJO_VERSION: 1.5.1

on:
  pull_request:
    paths-ignore:
      - "client/**"
      - "**/manifest.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scarb-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Scarb
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            contracts/target
          key: scarb-${{ hashFiles('contracts/Scarb.toml') }}
          restore-keys: |
            scarb-
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - run: cd contracts && scarb fmt --check

  sozo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Cache Dojo
        id: cache-dojo
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/sozo
          key: dojo-${{ env.DOJO_VERSION }}-linux-amd64
      
      - name: Download Dojo release artifact
        if: steps.cache-dojo.outputs.cache-hit != 'true'
        run: |
          curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/v${{ env.DOJO_VERSION }}/dojo_v${{ env.DOJO_VERSION }}_linux_amd64.tar.gz
          tar -xzf dojo-linux-x86_64.tar.gz
          sudo mv sozo /usr/local/bin/
      
      - name: Cache Scarb
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            contracts/target
          key: scarb-${{ hashFiles('contracts/Scarb.toml') }}
          restore-keys: |
            scarb-
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      
      - name: Run Dojo Build and Tests
        run: |
          cd contracts && sozo build && sozo test
