name: test-contracts

on:
  pull_request:
    paths:
      - "contracts/**"
      - ".tool-versions"
      - ".github/workflows/test-contract.yml"
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - ".tool-versions"
      - ".github/workflows/test-contract.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tool versions
        run: |
          DOJO_VERSION=$(grep '^dojo ' .tool-versions | awk '{print $2}')
          echo "DOJO_VERSION=$DOJO_VERSION" >> "$GITHUB_ENV"
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - name: Cache Dojo binary
        id: cache-dojo
        uses: actions/cache@v4
        with:
          path: ~/dojo-bin
          key: dojo-${{ env.DOJO_VERSION }}-${{ runner.os }}

      - name: Download and install Dojo
        if: steps.cache-dojo.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/dojo-bin
          curl -L https://github.com/dojoengine/dojo/releases/download/v${{ env.DOJO_VERSION }}/dojo_v${{ env.DOJO_VERSION }}_linux_amd64.tar.gz | tar -xz -C ~/dojo-bin

      - name: Add Dojo to PATH
        run: echo "$HOME/dojo-bin" >> $GITHUB_PATH

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Cache Scarb packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.scarb
            contracts/target
          key: scarb-${{ runner.os }}-${{ hashFiles('contracts/Scarb.lock') }}
          restore-keys: |
            scarb-${{ runner.os }}-

      - name: Check formatting
        run: |
          cd contracts && scarb fmt --check

      - name: Run Dojo Build
        run: |
          cd contracts && sozo build

      - name: Run Tests
        run: |
          cd contracts && sozo test
