name: test-contracts

on:
  pull_request:
    paths:
      - "contracts/**"
      - ".tool-versions"
      - ".github/workflows/test-contract.yml"
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - ".tool-versions"
      - ".github/workflows/test-contract.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tool versions
        run: |
          DOJO_VERSION=$(grep '^dojo ' .tool-versions | awk '{print $2}')
          echo "DOJO_VERSION=$DOJO_VERSION" >> "$GITHUB_ENV"
          SCARB_VERSION=$(grep '^scarb ' .tool-versions | awk '{print $2}')
          echo "SCARB_VERSION=$SCARB_VERSION" >> "$GITHUB_ENV"

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}

      - name: Check formatting
        run: |
          cd contracts && scarb fmt --check

      - name: Download and install Dojo
        run: |
          curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/v${{ env.DOJO_VERSION }}/dojo_v${{ env.DOJO_VERSION }}_linux_amd64.tar.gz
          tar -xzf dojo-linux-x86_64.tar.gz
          sudo mv sozo /usr/local/bin/

      - name: Run Dojo Build
        run: |
          cd contracts && sozo build

      - name: Run Tests
        run: |
          cd contracts && sozo test
